# config/services.yaml
parameters:
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    images_directory: '%kernel.project_dir%/public/uploads/images'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Explicit configuration for FacePlusPlusService
    App\Service\FacePlusPlusService:
        arguments:
            $apiKey: '%env(FACEPP_API_KEY)%'
            $apiSecret: '%env(FACEPP_API_SECRET)%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    # App\Service\StatisticsService will be automatically registered as a service
    App\Service\StatisticsService: ~
   
    # please note that last definitions always *replace* previous ones
